### ISSUE TITLE
Titan unable to find new paths

### ISSUE THREAD

**Issue by vannussina** [5hadowblad3/Titan#2]
Hi, I'm trying to fuzz libxml2 using Titan, but the fuzzer is unable to find new paths and the total number of paths equals the number of initial test cases. The test cases are the test files from the libxml2 repo.
This is my cstest.txt: 
```
dlfcn.c:1208
dict.c:318
relaxng.c:1
fuzz.c:222
xinclude.c:83
encoding.c:1049
xml.c:36
schema.c:20
xinclude.c:1
testOOM.c:101
xmlcatalog.c:604
ianatables.c:1390
catalog.c:1
xpath2.c:180
libxmlmain.c:33
xmlunicode.c:1
runxmlconf.c:599
xmlreader.c:1
xmlwriter.c:1
xmlwriter.c:1
valid.c:36
xpath.c:28
list.c:117
```

and the AFL output: 
![Screenshot from 2023-12-03 16-42-36](https://github.com/5hadowblad3/Titan/assets/77995129/732b2244-de53-480a-bf92-62227bcb755b)

What does the number mean that is labeled by 'violated'?
Thanks in advance, it would be great if I could use Titan for my project as I need the multi-target approach.

**Comment by vannussina** [comment]
I just found my error, I forgot to build with debug symbols.

But I'd still would be interested in what the `violated` value means. Thanks!

**Comment by 5hadowblad3** [comment]
Sorry for the late reply. I thought I had responded to you previously, but it seems the response was not sent.

For the `violated`, it is one of the testing parameters for some new features inherited from our previous work, [Beacon](https://github.com/5hadowblad3/Beacon_artifact).

Hope you have a good time in exploring our framework!

**Comment by vannussina** [comment]
Alright, thanks for your answer!

**Comment by null1024-ws** [comment]
> I just found my error, I forgot to build with debug symbols.
> 
> But I'd still would be interested in what the `violated` value means. Thanks!

hello could you please share your build cmd for libxml2 project?
