### ISSUE TITLE
Fix tips and questions

### ISSUE THREAD

**Issue by CXWorks** [5hadowblad3/Titan#4]
Hi,

Thanks for open sourcing your project. I'm managed to launch your project under a Ubuntu18.04 docker and willing to share if you want. During the running, I found following questions or comments:

1. In 3.2.2 step, I'm providing the location info and for testing, I provide the `main` function, is it expected to get empty files for `bug_conf_cluster` and `bug_over_cluster`? 
2. In 3.2.3 step, the output file `fuzz.bc` is actually a `.ll` file and needs to be further changed to `fuzz.bc`. Besides, in the following steps, `fuzz.bc` should be used for generating the final fuzz binary, not the `transed.bc` shown in the instruction.

Thanks again for your help!

**Comment by 5hadowblad3** [comment]
>In 3.2.2 step, I'm providing the location info and for testing, I provide the main function, is it expected to get empty files for bug_conf_cluster and bug_over_cluster?

I am not sure what you mean by providing the main function. Usually, empty files mean our analysis does not analyze any target or there are no conditional instructions before all the targets, such as the entry of main functions.

> In 3.2.3 step, the output file fuzz.bc is actually a .ll file and needs to be further changed to fuzz.bc.

.ll can be directly compiled into binary in LLVM 4 using Clang if I remember correctly.

> Besides, in the following steps, fuzz.bc should be used for generating the final fuzz binary, not the transed.bc shown in the instruction.

Thanks! I have corrected it!
